spring.application.name: configserver

server.port: 8888

spring.profiles.active: vault, git

spring.cloud.config.server.vault.host: 127.0.0.1
spring.cloud.config.server.vault.port: 8200
spring.cloud.config.server.vault.scheme: http
spring.cloud.config.server.vault.kv-version: 2
spring.cloud.config.server.vault.authentication: TOKEN
spring.cloud.config.server.vault.token: root
spring.cloud.config.server.vault.order: 1

spring.cloud.config.server.git.uri: https://github.com/<username>/<repository>
spring.cloud.config.server.git.searchPaths: "{application}"
spring.cloud.config.server.git.username: your_github_username
spring.cloud.config.server.git.password: your_github_token
spring.cloud.config.server.git.force-pull: true
spring.cloud.config.server.git.order: 2

spring.security.user.name: your_username
spring.security.user.password: your_password